#ifndef SUMIRE_VERSION_H
#define SUMIRE_VERSION_H

#define SUMIRE_VERSION_MAJOR 0
#define SUMIRE_VERSION_MINOR 1
#define SUMIRE_VERSION_PATCH 0
#define SUMIRE_VERSION_BUILD 0

#define SUMIRE_VERSION_STRING "0.1.0.0"
#define SUMIRE_VERSION_WSTRING L"0.1.0.0"

#define SUMIRE_PRODUCT_NAME "Sumire IME"
#define SUMIRE_PRODUCT_NAME_W L"Sumire IME"
#define SUMIRE_COMPANY_NAME "Sumire"
#define SUMIRE_COMPANY_NAME_W L"Sumire"
#define SUMIRE_LEGAL_COPYRIGHT "Copyright (C) 2026 Sumire"

#endif // SUMIRE_VERSION_H
